language: node_js
before_install:
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-5 g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 80 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - sudo update-alternatives --set gcc /usr/bin/gcc-5
node_js:
  - 5.1.0
script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - cd styleguide/structure/_node-files
  - npm install tape faucet browserify nightwatch
  - npm install
  - cd ../_tests
  - node structure-node-dependencies.js
  - node structure-node-modules.js
  - node structure-node-integration.js
  - node structure-front-scripts.js
  - ../_node-files/node_modules/.bin/nightwatch --test structure-end-2-end.js
